# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 429)
        MainWindow.setMinimumSize(QtCore.QSize(480, 429))
        MainWindow.setMaximumSize(QtCore.QSize(480, 429))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/catCook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 8pt \"STXihei\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 481, 433))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(22, 11, 22, 22)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headerProdHorizontalLayout = QtWidgets.QHBoxLayout()
        self.headerProdHorizontalLayout.setObjectName("headerProdHorizontalLayout")
        self.chooseMenuHeaderLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.chooseMenuHeaderLabel.setEnabled(True)
        self.chooseMenuHeaderLabel.setMinimumSize(QtCore.QSize(0, 36))
        self.chooseMenuHeaderLabel.setMaximumSize(QtCore.QSize(16777215, 36))
        self.chooseMenuHeaderLabel.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"\n"
"width: 435px;\n"
"height: 24px;\n"
"\n"
"font: 16pt \"Extra Bold\";\n"
"\n"
"font-weight: 800;\n"
"text-align: left;\n"
"vertical-align: top")
        self.chooseMenuHeaderLabel.setObjectName("chooseMenuHeaderLabel")
        self.headerProdHorizontalLayout.addWidget(self.chooseMenuHeaderLabel)
        self.verticalLayout_2.addLayout(self.headerProdHorizontalLayout)
        self.itemsGridLayout = QtWidgets.QGridLayout()
        self.itemsGridLayout.setObjectName("itemsGridLayout")
        self.item3pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.item3pushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"border: 2 px solid #ADFF81;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}\n"
"\n"
"")
        self.item3pushButton.setObjectName("item3pushButton")
        self.itemsGridLayout.addWidget(self.item3pushButton, 2, 0, 1, 1)
        self.item5pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.item5pushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"border: 2 px solid #ADFF81;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}\n"
"\n"
"")
        self.item5pushButton.setObjectName("item5pushButton")
        self.itemsGridLayout.addWidget(self.item5pushButton, 3, 0, 1, 1)
        self.item1pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.item1pushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"border: 2 px solid #ADFF81;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}\n"
"\n"
"")
        self.item1pushButton.setObjectName("item1pushButton")
        self.itemsGridLayout.addWidget(self.item1pushButton, 1, 0, 1, 1)
        self.item4pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.item4pushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"border: 2 px solid #ADFF81;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}\n"
"\n"
"")
        self.item4pushButton.setObjectName("item4pushButton")
        self.itemsGridLayout.addWidget(self.item4pushButton, 2, 1, 1, 1)
        self.item6pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.item6pushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"border: 2 px solid #ADFF81;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}\n"
"\n"
"")
        self.item6pushButton.setObjectName("item6pushButton")
        self.itemsGridLayout.addWidget(self.item6pushButton, 3, 1, 1, 1)
        self.item2pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.item2pushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"border: 2 px solid #ADFF81;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}\n"
"\n"
"")
        self.item2pushButton.setObjectName("item2pushButton")
        self.itemsGridLayout.addWidget(self.item2pushButton, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.itemsGridLayout)
        self.breakfastVerticalLayout = QtWidgets.QVBoxLayout()
        self.breakfastVerticalLayout.setObjectName("breakfastVerticalLayout")
        self.breakfastHeaderLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.breakfastHeaderLabel.setMinimumSize(QtCore.QSize(0, 36))
        self.breakfastHeaderLabel.setMaximumSize(QtCore.QSize(16777215, 36))
        self.breakfastHeaderLabel.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"\n"
"width: 435px;\n"
"height: 24px;\n"
"\n"
"font-size: 20px;\n"
"font-family: Inter, \"Extra Bold\";\n"
"font-weight: 800;\n"
"text-align: left;\n"
"vertical-align: top")
        self.breakfastHeaderLabel.setObjectName("breakfastHeaderLabel")
        self.breakfastVerticalLayout.addWidget(self.breakfastHeaderLabel)
        self.breakfastLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.breakfastLabel.setStyleSheet("color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.breakfastLabel.setObjectName("breakfastLabel")
        self.breakfastVerticalLayout.addWidget(self.breakfastLabel)
        self.verticalLayout_2.addLayout(self.breakfastVerticalLayout)
        self.lunchVerticalLayout = QtWidgets.QVBoxLayout()
        self.lunchVerticalLayout.setObjectName("lunchVerticalLayout")
        self.lunchHeaderLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lunchHeaderLabel.setMinimumSize(QtCore.QSize(0, 36))
        self.lunchHeaderLabel.setMaximumSize(QtCore.QSize(16777215, 36))
        self.lunchHeaderLabel.setStyleSheet("  width: 435px;\n"
"  height: 24px;\n"
"  color: #2d2c2c;\n"
"  font-size: 20px;\n"
"  font-family: Inter, \"Extra Bold\";\n"
"  font-weight: 800;\n"
"  text-align: left;\n"
"  vertical-align: top")
        self.lunchHeaderLabel.setObjectName("lunchHeaderLabel")
        self.lunchVerticalLayout.addWidget(self.lunchHeaderLabel)
        self.lunchLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lunchLabel.setStyleSheet("color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.lunchLabel.setObjectName("lunchLabel")
        self.lunchVerticalLayout.addWidget(self.lunchLabel)
        self.verticalLayout_2.addLayout(self.lunchVerticalLayout)
        self.dinerDerticalLayout = QtWidgets.QVBoxLayout()
        self.dinerDerticalLayout.setObjectName("dinerDerticalLayout")
        self.dinerHeaderLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dinerHeaderLabel.setMinimumSize(QtCore.QSize(0, 36))
        self.dinerHeaderLabel.setMaximumSize(QtCore.QSize(16777215, 36))
        self.dinerHeaderLabel.setStyleSheet("  width: 435px;\n"
"  height: 24px;\n"
"  color: #2d2c2c;\n"
"  font-size: 20px;\n"
"  font-family: Inter, \"Extra Bold\";\n"
"  font-weight: 800;\n"
"  text-align: left;\n"
"  vertical-align: top")
        self.dinerHeaderLabel.setObjectName("dinerHeaderLabel")
        self.dinerDerticalLayout.addWidget(self.dinerHeaderLabel)
        self.dinerLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dinerLabel.setStyleSheet("color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.dinerLabel.setObjectName("dinerLabel")
        self.dinerDerticalLayout.addWidget(self.dinerLabel)
        self.verticalLayout_2.addLayout(self.dinerDerticalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Умное меню - составить меню"))
        self.chooseMenuHeaderLabel.setText(_translate("MainWindow", "Что хотите на завтрак?"))
        self.item3pushButton.setText(_translate("MainWindow", "item3pushButton"))
        self.item5pushButton.setText(_translate("MainWindow", "item5pushButton"))
        self.item1pushButton.setText(_translate("MainWindow", "item1pushButton"))
        self.item4pushButton.setText(_translate("MainWindow", "item4pushButton"))
        self.item6pushButton.setText(_translate("MainWindow", "item6pushButton"))
        self.item2pushButton.setText(_translate("MainWindow", "item2pushButton"))
        self.breakfastHeaderLabel.setText(_translate("MainWindow", "Завтрак:"))
        self.breakfastLabel.setText(_translate("MainWindow", "Пока нет..."))
        self.lunchHeaderLabel.setText(_translate("MainWindow", "Обед:"))
        self.lunchLabel.setText(_translate("MainWindow", "Пока нет..."))
        self.dinerHeaderLabel.setText(_translate("MainWindow", "Ужин:"))
        self.dinerLabel.setText(_translate("MainWindow", "Пока нет..."))
