# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_add_storage_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(542, 218)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalFrame = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame.setGeometry(QtCore.QRect(0, 0, 540, 220))
        self.verticalFrame.setMinimumSize(QtCore.QSize(540, 220))
        self.verticalFrame.setMaximumSize(QtCore.QSize(540, 220))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setContentsMargins(22, 11, 22, 22)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addStorageHeaderLabel = QtWidgets.QLabel(self.verticalFrame)
        self.addStorageHeaderLabel.setEnabled(True)
        self.addStorageHeaderLabel.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"\n"
"width: 435px;\n"
"height: 24px;\n"
"margin-top: 8px;\n"
"margin-bottom:8px;\n"
"\n"
"font-size: 20px;\n"
"font-family: Inter, \"Extra Bold\";\n"
"font-weight: 800;\n"
"text-align: left;\n"
"vertical-align: top")
        self.addStorageHeaderLabel.setObjectName("addStorageHeaderLabel")
        self.verticalLayout_2.addWidget(self.addStorageHeaderLabel)
        self.storeHorizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.storeHorizontalLayout_3.setObjectName("storeHorizontalLayout_3")
        self.storeComboBox = QtWidgets.QComboBox(self.verticalFrame)
        self.storeComboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.storeComboBox.setAccessibleName("")
        self.storeComboBox.setStyleSheet("QComboBox {\n"
"    background-color: #ffffff; /* Цвет фона */\n"
"    border-radius: 4%; /* Радиус границы */\n"
"    border: 2px solid rgba(100, 100, 100, 25); /* Граница */\n"
"    color: #2d2c2c; /* Цвет текста */\n"
"    height: 32px; /* Высота */\n"
"    padding-left: 8px; /* Отступ для текста */\n"
"    font-size: 14px; /* Размер шрифта */\n"
"    font-family: Inter; /* Шрифт */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 32px; /* Ширина кнопки */\n"
"    border: none; /* Убираем границы у кнопки с треугольником */\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"    width: 0px;  /* Убираем стандартные индикаторы */\n"
"    height: 0px; /* Убираем стандартные индикаторы */\n"
"}\n"
"\n"
"QComboBox::drop-down:after {\n"
"    content: \'\'; /* Создаем псевдоэлемент для треугольника */\n"
"    position: absolute;\n"
"    right: 10px; /* Положение треугольника (по желанию) */\n"
"    top: 50%; /* Центрируем по вертикали */\n"
"    transform: translateY(-50%); /* Центрирование */\n"
"    border-left: 5px solid transparent; /* Левый делитель */\n"
"    border-right: 5px solid transparent; /* Правый делитель */\n"
"    border-top: 5px solid #2d2c2c; /* Цвет треугольника */\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    background-color: #AAAAFF; /* Цвет при нажатии */\n"
"}")
        self.storeComboBox.setDuplicatesEnabled(False)
        self.storeComboBox.setFrame(True)
        self.storeComboBox.setObjectName("storeComboBox")
        self.storeComboBox.addItem("")
        self.storeHorizontalLayout_3.addWidget(self.storeComboBox)
        self.storeSpinBox = QtWidgets.QSpinBox(self.verticalFrame)
        self.storeSpinBox.setMinimumSize(QtCore.QSize(92, 0))
        self.storeSpinBox.setMaximumSize(QtCore.QSize(92, 16777215))
        self.storeSpinBox.setStyleSheet("background-color:#ffffff;\n"
"border-radius:4%;\n"
"border:2px solid rgba(100, 100, 100, 25);\n"
"\n"
"color: #2d2c2c;\n"
"\n"
"width:40px;\n"
"height:32px;\n"
"\n"
"padding-left: 8px;\n"
"position:absolute;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"left:12px;\n"
"top:8px;")
        self.storeSpinBox.setObjectName("storeSpinBox")
        self.storeHorizontalLayout_3.addWidget(self.storeSpinBox)
        self.unitStoregaItemLoabel = QtWidgets.QLabel(self.verticalFrame)
        self.unitStoregaItemLoabel.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"margin-top: 8px;\n"
"margin-bottom:8px;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"min-width: 56px;\n"
"max-width: 56px;")
        self.unitStoregaItemLoabel.setScaledContents(False)
        self.unitStoregaItemLoabel.setWordWrap(True)
        self.unitStoregaItemLoabel.setObjectName("unitStoregaItemLoabel")
        self.storeHorizontalLayout_3.addWidget(self.unitStoregaItemLoabel)
        self.verticalLayout_2.addLayout(self.storeHorizontalLayout_3)
        self.purchaseHorizontalLayout = QtWidgets.QHBoxLayout()
        self.purchaseHorizontalLayout.setObjectName("purchaseHorizontalLayout")
        self.spaceLabel = QtWidgets.QLabel(self.verticalFrame)
        self.spaceLabel.setText("")
        self.spaceLabel.setObjectName("spaceLabel")
        self.purchaseHorizontalLayout.addWidget(self.spaceLabel)
        self.purchaseDateLabel = QtWidgets.QLabel(self.verticalFrame)
        self.purchaseDateLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.purchaseDateLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.purchaseDateLabel.setStyleSheet("background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.purchaseDateLabel.setScaledContents(False)
        self.purchaseDateLabel.setWordWrap(True)
        self.purchaseDateLabel.setObjectName("purchaseDateLabel")
        self.purchaseHorizontalLayout.addWidget(self.purchaseDateLabel)
        self.purchaseDateDateEdit = QtWidgets.QDateEdit(self.verticalFrame)
        self.purchaseDateDateEdit.setStyleSheet("background-color:#ffffff;\n"
"border-radius:4%;\n"
"border:2px solid rgba(100, 100, 100, 25);\n"
"\n"
"color: #2d2c2c;\n"
"\n"
"width:360px;\n"
"height:32px;\n"
"\n"
"padding-left: 8px;\n"
"position:absolute;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"left:12px;\n"
"top:8px;")
        self.purchaseDateDateEdit.setObjectName("purchaseDateDateEdit")
        self.purchaseHorizontalLayout.addWidget(self.purchaseDateDateEdit)
        self.verticalLayout_2.addLayout(self.purchaseHorizontalLayout)
        self.actionsStorageHorizontalLayout = QtWidgets.QHBoxLayout()
        self.actionsStorageHorizontalLayout.setObjectName("actionsStorageHorizontalLayout")
        self.addStoragePushButton = QtWidgets.QPushButton(self.verticalFrame)
        self.addStoragePushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"margin-top: 16px;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"border: 2 px solid #ADFF81;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}\n"
"\n"
"\n"
"")
        self.addStoragePushButton.setObjectName("addStoragePushButton")
        self.actionsStorageHorizontalLayout.addWidget(self.addStoragePushButton)
        self.cancelStorageItemPushButton = QtWidgets.QPushButton(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelStorageItemPushButton.sizePolicy().hasHeightForWidth())
        self.cancelStorageItemPushButton.setSizePolicy(sizePolicy)
        self.cancelStorageItemPushButton.setMinimumSize(QtCore.QSize(48, 48))
        self.cancelStorageItemPushButton.setMaximumSize(QtCore.QSize(48, 48))
        self.cancelStorageItemPushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"margin-top: 16px;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"border: 2px solid rgba(146, 146, 120, 75);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}")
        self.cancelStorageItemPushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/bx_trash.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelStorageItemPushButton.setIcon(icon)
        self.cancelStorageItemPushButton.setIconSize(QtCore.QSize(24, 24))
        self.cancelStorageItemPushButton.setObjectName("cancelStorageItemPushButton")
        self.actionsStorageHorizontalLayout.addWidget(self.cancelStorageItemPushButton)
        self.verticalLayout_2.addLayout(self.actionsStorageHorizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addStorageHeaderLabel.setText(_translate("MainWindow", "Заполните информацию о покупке"))
        self.storeComboBox.setCurrentText(_translate("MainWindow", "Помидор"))
        self.storeComboBox.setItemText(0, _translate("MainWindow", "Помидор"))
        self.unitStoregaItemLoabel.setText(_translate("MainWindow", "ед."))
        self.purchaseDateLabel.setText(_translate("MainWindow", "Дата покупки:"))
        self.addStoragePushButton.setText(_translate("MainWindow", "Сохранить"))
