# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_prod.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 271)
        MainWindow.setMinimumSize(QtCore.QSize(540, 0))
        MainWindow.setMaximumSize(QtCore.QSize(540, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/catCook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 8pt \"STXihei\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(540, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(540, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalFrame = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame.setGeometry(QtCore.QRect(0, 0, 540, 271))
        self.verticalFrame.setMinimumSize(QtCore.QSize(540, 0))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setContentsMargins(22, 11, 22, 22)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.verticalFrame)
        self.label_8.setEnabled(True)
        self.label_8.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"\n"
"width: 435px;\n"
"height: 24px;\n"
"\n"
"font: 16pt \"Extra Bold\";\n"
"\n"
"font-weight: 800;\n"
"text-align: left;\n"
"vertical-align: top")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.nameOProdLineEdit = QtWidgets.QLineEdit(self.verticalFrame)
        self.nameOProdLineEdit.setStyleSheet("background-color:#ffffff;\n"
"border-radius:4%;\n"
"border:2px solid rgba(100, 100, 100, 25);\n"
"\n"
"color: #2d2c2c;\n"
"\n"
"height:32px;\n"
"\n"
"padding-left: 8px;\n"
"position:absolute;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"\n"
"font-size:14px;\n"
"left:12px;\n"
"top:8px;")
        self.nameOProdLineEdit.setText("")
        self.nameOProdLineEdit.setMaxLength(32770)
        self.nameOProdLineEdit.setCursorPosition(0)
        self.nameOProdLineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.nameOProdLineEdit.setClearButtonEnabled(False)
        self.nameOProdLineEdit.setObjectName("nameOProdLineEdit")
        self.horizontalLayout_3.addWidget(self.nameOProdLineEdit)
        self.unitComboBox = QtWidgets.QComboBox(self.verticalFrame)
        self.unitComboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.unitComboBox.setAccessibleName("")
        self.unitComboBox.setStyleSheet("QComboBox {\n"
"    background-color: #ffffff; /* Цвет фона */\n"
"    border-radius: 4%; /* Радиус границы */\n"
"    border: 2px solid rgba(100, 100, 100, 25); /* Граница */\n"
"    color: #2d2c2c; /* Цвет текста */\n"
"    width: 25px; /* Ширина */\n"
"    height: 32px; /* Высота */\n"
"    padding-left: 8px; /* Отступ для текста */\n"
"    font-size: 14px; /* Размер шрифта */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 32px; /* Ширина кнопки */\n"
"    border: none; /* Убираем границы у кнопки с треугольником */\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"    width: 0px;  /* Убираем стандартные индикаторы */\n"
"    height: 0px; /* Убираем стандартные индикаторы */\n"
"}\n"
"\n"
"QComboBox::drop-down:after {\n"
"    content: \'\'; /* Создаем псевдоэлемент для треугольника */\n"
"    position: absolute;\n"
"    right: 10px; /* Положение треугольника (по желанию) */\n"
"    top: 50%; /* Центрируем по вертикали */\n"
"    transform: translateY(-50%); /* Центрирование */\n"
"    border-left: 5px solid transparent; /* Левый делитель */\n"
"    border-right: 5px solid transparent; /* Правый делитель */\n"
"    border-top: 5px solid #2d2c2c; /* Цвет треугольника */\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    background-color: #AAAAFF; /* Цвет при нажатии */\n"
"}")
        self.unitComboBox.setCurrentText("")
        self.unitComboBox.setDuplicatesEnabled(False)
        self.unitComboBox.setFrame(True)
        self.unitComboBox.setObjectName("unitComboBox")
        self.horizontalLayout_3.addWidget(self.unitComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.kaloriesLineEdit = QtWidgets.QLineEdit(self.verticalFrame)
        self.kaloriesLineEdit.setStyleSheet("background-color:#ffffff;\n"
"border-radius:4%;\n"
"border:2px solid rgba(100, 100, 100, 25);\n"
"\n"
"color: #2d2c2c;\n"
"\n"
"width:360px;\n"
"height:32px;\n"
"\n"
"padding-left: 8px;\n"
"position:absolute;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"\n"
"font-size:14px;\n"
"left:12px;\n"
"top:8px;")
        self.kaloriesLineEdit.setText("")
        self.kaloriesLineEdit.setCursorPosition(0)
        self.kaloriesLineEdit.setClearButtonEnabled(False)
        self.kaloriesLineEdit.setObjectName("kaloriesLineEdit")
        self.horizontalLayout_2.addWidget(self.kaloriesLineEdit)
        self.proteinsLineEdit = QtWidgets.QLineEdit(self.verticalFrame)
        self.proteinsLineEdit.setMinimumSize(QtCore.QSize(46, 0))
        self.proteinsLineEdit.setMaximumSize(QtCore.QSize(46, 16777215))
        self.proteinsLineEdit.setStyleSheet("background-color:#ffffff;\n"
"border-radius:4%;\n"
"border:2px solid rgba(100, 100, 100, 25);\n"
"\n"
"color: #2d2c2c;\n"
"\n"
"height:32px;\n"
"\n"
"padding-left: 8px;\n"
"position:absolute;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"\n"
"font-size:14px;\n"
"left:12px;\n"
"top:8px;")
        self.proteinsLineEdit.setText("")
        self.proteinsLineEdit.setCursorPosition(0)
        self.proteinsLineEdit.setClearButtonEnabled(False)
        self.proteinsLineEdit.setObjectName("proteinsLineEdit")
        self.horizontalLayout_2.addWidget(self.proteinsLineEdit)
        self.fatsLineEdit = QtWidgets.QLineEdit(self.verticalFrame)
        self.fatsLineEdit.setMinimumSize(QtCore.QSize(46, 0))
        self.fatsLineEdit.setMaximumSize(QtCore.QSize(46, 16777215))
        self.fatsLineEdit.setStyleSheet("background-color:#ffffff;\n"
"border-radius:4%;\n"
"border:2px solid rgba(100, 100, 100, 25);\n"
"\n"
"color: #2d2c2c;\n"
"\n"
"height:32px;\n"
"\n"
"padding-left: 8px;\n"
"position:absolute;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"\n"
"font-size:14px;\n"
"left:12px;\n"
"top:8px;")
        self.fatsLineEdit.setText("")
        self.fatsLineEdit.setCursorPosition(0)
        self.fatsLineEdit.setClearButtonEnabled(False)
        self.fatsLineEdit.setObjectName("fatsLineEdit")
        self.horizontalLayout_2.addWidget(self.fatsLineEdit)
        self.carbohLineEdit = QtWidgets.QLineEdit(self.verticalFrame)
        self.carbohLineEdit.setMinimumSize(QtCore.QSize(46, 0))
        self.carbohLineEdit.setMaximumSize(QtCore.QSize(46, 16777215))
        self.carbohLineEdit.setStyleSheet("background-color:#ffffff;\n"
"border-radius:4%;\n"
"border:2px solid rgba(100, 100, 100, 25);\n"
"\n"
"color: #2d2c2c;\n"
"\n"
"height:32px;\n"
"\n"
"padding-left: 8px;\n"
"position:absolute;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"\n"
"font-size:14px;\n"
"left:12px;\n"
"top:8px;")
        self.carbohLineEdit.setText("")
        self.carbohLineEdit.setCursorPosition(0)
        self.carbohLineEdit.setClearButtonEnabled(False)
        self.carbohLineEdit.setObjectName("carbohLineEdit")
        self.horizontalLayout_2.addWidget(self.carbohLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.spaseLabel = QtWidgets.QLabel(self.verticalFrame)
        self.spaseLabel.setText("")
        self.spaseLabel.setObjectName("spaseLabel")
        self.horizontalLayout_4.addWidget(self.spaseLabel)
        self.lifeLabel = QtWidgets.QLabel(self.verticalFrame)
        self.lifeLabel.setStyleSheet("background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;")
        self.lifeLabel.setScaledContents(False)
        self.lifeLabel.setWordWrap(True)
        self.lifeLabel.setObjectName("lifeLabel")
        self.horizontalLayout_4.addWidget(self.lifeLabel)
        self.shelfLifeLineEdit = QtWidgets.QLineEdit(self.verticalFrame)
        self.shelfLifeLineEdit.setStyleSheet("background-color:#ffffff;\n"
"border-radius:4%;\n"
"border:2px solid rgba(100, 100, 100, 25);\n"
"\n"
"color: #2d2c2c;\n"
"\n"
"width:320px;\n"
"height:32px;\n"
"\n"
"padding-left: 8px;\n"
"position:absolute;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"\n"
"font-size:14px;\n"
"left:12px;\n"
"top:8px;")
        self.shelfLifeLineEdit.setText("")
        self.shelfLifeLineEdit.setCursorPosition(0)
        self.shelfLifeLineEdit.setClearButtonEnabled(False)
        self.shelfLifeLineEdit.setObjectName("shelfLifeLineEdit")
        self.horizontalLayout_4.addWidget(self.shelfLifeLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.addProdPushButton = QtWidgets.QPushButton(self.verticalFrame)
        self.addProdPushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"margin-top: 16px;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"border: 2 px solid #ADFF81;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}\n"
"\n"
"\n"
"")
        self.addProdPushButton.setObjectName("addProdPushButton")
        self.verticalLayout_2.addWidget(self.addProdPushButton)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Умное меню - Добавить продукт"))
        self.label_8.setText(_translate("MainWindow", "Заполните информацию о продукте"))
        self.nameOProdLineEdit.setPlaceholderText(_translate("MainWindow", "Введите название продукта"))
        self.kaloriesLineEdit.setPlaceholderText(_translate("MainWindow", "Введите количество калорий"))
        self.proteinsLineEdit.setPlaceholderText(_translate("MainWindow", "Б:"))
        self.fatsLineEdit.setPlaceholderText(_translate("MainWindow", "Ж:"))
        self.carbohLineEdit.setPlaceholderText(_translate("MainWindow", "У:"))
        self.lifeLabel.setText(_translate("MainWindow", "Срок годности:"))
        self.shelfLifeLineEdit.setPlaceholderText(_translate("MainWindow", "дней (целое число)"))
        self.addProdPushButton.setText(_translate("MainWindow", "Добавить"))
