# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ispect_dish.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 602)
        MainWindow.setMinimumSize(QtCore.QSize(540, 0))
        MainWindow.setMaximumSize(QtCore.QSize(540, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/catCook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"font: 8pt \"STXihei\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalFrame = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame.setGeometry(QtCore.QRect(0, 0, 542, 608))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setContentsMargins(22, 11, 22, 22)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addDishHeaderLabel = QtWidgets.QLabel(self.verticalFrame)
        self.addDishHeaderLabel.setEnabled(True)
        self.addDishHeaderLabel.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"\n"
"width: 435px;\n"
"height: 24px;\n"
"\n"
"font: 16pt \"Extra Bold\";\n"
"\n"
"font-weight: 800;\n"
"text-align: left;\n"
"vertical-align: top")
        self.addDishHeaderLabel.setObjectName("addDishHeaderLabel")
        self.verticalLayout_2.addWidget(self.addDishHeaderLabel)
        self.nutritiansHorizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.nutritiansHorizontalLayout_2.setObjectName("nutritiansHorizontalLayout_2")
        self.unitIngredLoabel_6 = QtWidgets.QLabel(self.verticalFrame)
        self.unitIngredLoabel_6.setMinimumSize(QtCore.QSize(0, 0))
        self.unitIngredLoabel_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.unitIngredLoabel_6.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"margin-top: 8px;\n"
"margin-bottom:8px;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"")
        self.unitIngredLoabel_6.setScaledContents(False)
        self.unitIngredLoabel_6.setWordWrap(True)
        self.unitIngredLoabel_6.setObjectName("unitIngredLoabel_6")
        self.nutritiansHorizontalLayout_2.addWidget(self.unitIngredLoabel_6)
        self.nameOfDishLineEdit = QtWidgets.QLineEdit(self.verticalFrame)
        self.nameOfDishLineEdit.setStyleSheet("background-color:#ffffff;\n"
"border-radius:4%;\n"
"border:2px solid rgba(100, 100, 100, 25);\n"
"\n"
"color: #2d2c2c;\n"
"\n"
"width:320px;\n"
"height:32px;\n"
"\n"
"padding-left: 8px;\n"
"position:absolute;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"\n"
"font-size:14px;\n"
"left:12px;\n"
"top:8px;")
        self.nameOfDishLineEdit.setText("")
        self.nameOfDishLineEdit.setMaxLength(32770)
        self.nameOfDishLineEdit.setCursorPosition(0)
        self.nameOfDishLineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.nameOfDishLineEdit.setClearButtonEnabled(False)
        self.nameOfDishLineEdit.setObjectName("nameOfDishLineEdit")
        self.nutritiansHorizontalLayout_2.addWidget(self.nameOfDishLineEdit)
        self.verticalLayout_2.addLayout(self.nutritiansHorizontalLayout_2)
        self.infoDishPlainTextEdit = QtWidgets.QPlainTextEdit(self.verticalFrame)
        self.infoDishPlainTextEdit.setStyleSheet("background-color:#ffffff;\n"
"border-radius:4%;\n"
"border:2px solid rgba(100, 100, 100, 25);\n"
"\n"
"color: #2d2c2c;\n"
"\n"
"width:360px;\n"
"height:32px;\n"
"\n"
"padding: 8px;\n"
"position:absolute;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"\n"
"font-size:14px;\n"
"left:12px;\n"
"top:8px;")
        self.infoDishPlainTextEdit.setPlainText("")
        self.infoDishPlainTextEdit.setObjectName("infoDishPlainTextEdit")
        self.verticalLayout_2.addWidget(self.infoDishPlainTextEdit)
        self.calculateAutoNutritValuecheckBox = QtWidgets.QCheckBox(self.verticalFrame)
        self.calculateAutoNutritValuecheckBox.setEnabled(True)
        self.calculateAutoNutritValuecheckBox.setStyleSheet("margin-top: 8px;\n"
"background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.calculateAutoNutritValuecheckBox.setChecked(False)
        self.calculateAutoNutritValuecheckBox.setObjectName("calculateAutoNutritValuecheckBox")
        self.verticalLayout_2.addWidget(self.calculateAutoNutritValuecheckBox)
        self.nutritiansHorizontalLayout = QtWidgets.QHBoxLayout()
        self.nutritiansHorizontalLayout.setObjectName("nutritiansHorizontalLayout")
        self.unitIngredLoabel_4 = QtWidgets.QLabel(self.verticalFrame)
        self.unitIngredLoabel_4.setMinimumSize(QtCore.QSize(56, 0))
        self.unitIngredLoabel_4.setMaximumSize(QtCore.QSize(56, 16777215))
        self.unitIngredLoabel_4.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"margin-top: 8px;\n"
"margin-bottom:8px;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"min-width: 56px;\n"
"max-width: 56px;")
        self.unitIngredLoabel_4.setScaledContents(False)
        self.unitIngredLoabel_4.setWordWrap(True)
        self.unitIngredLoabel_4.setObjectName("unitIngredLoabel_4")
        self.nutritiansHorizontalLayout.addWidget(self.unitIngredLoabel_4)
        self.kaloriesLineEdit = QtWidgets.QLineEdit(self.verticalFrame)
        self.kaloriesLineEdit.setStyleSheet("background-color:#ffffff;\n"
"border-radius:4%;\n"
"border:2px solid rgba(100, 100, 100, 25);\n"
"\n"
"color: #2d2c2c;\n"
"\n"
"width:360px;\n"
"height:32px;\n"
"\n"
"padding-left: 8px;\n"
"position:absolute;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"\n"
"font-size:14px;\n"
"left:12px;\n"
"top:8px;")
        self.kaloriesLineEdit.setText("")
        self.kaloriesLineEdit.setFrame(True)
        self.kaloriesLineEdit.setCursorPosition(0)
        self.kaloriesLineEdit.setClearButtonEnabled(False)
        self.kaloriesLineEdit.setObjectName("kaloriesLineEdit")
        self.nutritiansHorizontalLayout.addWidget(self.kaloriesLineEdit)
        self.unitIngredLoabel_1 = QtWidgets.QLabel(self.verticalFrame)
        self.unitIngredLoabel_1.setMinimumSize(QtCore.QSize(20, 0))
        self.unitIngredLoabel_1.setMaximumSize(QtCore.QSize(20, 16777215))
        self.unitIngredLoabel_1.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"margin-top: 8px;\n"
"margin-bottom:8px;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"min-width: 20px;\n"
"max-width: 20px;")
        self.unitIngredLoabel_1.setScaledContents(False)
        self.unitIngredLoabel_1.setWordWrap(True)
        self.unitIngredLoabel_1.setObjectName("unitIngredLoabel_1")
        self.nutritiansHorizontalLayout.addWidget(self.unitIngredLoabel_1)
        self.proteinsLineEdit = QtWidgets.QLineEdit(self.verticalFrame)
        self.proteinsLineEdit.setMinimumSize(QtCore.QSize(46, 0))
        self.proteinsLineEdit.setMaximumSize(QtCore.QSize(46, 16777215))
        self.proteinsLineEdit.setStyleSheet("background-color:#ffffff;\n"
"border-radius:4%;\n"
"border:2px solid rgba(100, 100, 100, 25);\n"
"\n"
"color: #2d2c2c;\n"
"\n"
"height:32px;\n"
"\n"
"padding-left: 8px;\n"
"position:absolute;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"\n"
"font-size:14px;\n"
"left:12px;\n"
"top:8px;")
        self.proteinsLineEdit.setText("")
        self.proteinsLineEdit.setCursorPosition(0)
        self.proteinsLineEdit.setClearButtonEnabled(False)
        self.proteinsLineEdit.setObjectName("proteinsLineEdit")
        self.nutritiansHorizontalLayout.addWidget(self.proteinsLineEdit)
        self.unitIngredLoabel_2 = QtWidgets.QLabel(self.verticalFrame)
        self.unitIngredLoabel_2.setMinimumSize(QtCore.QSize(20, 0))
        self.unitIngredLoabel_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.unitIngredLoabel_2.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"margin-top: 8px;\n"
"margin-bottom:8px;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"min-width: 20px;\n"
"max-width: 20px;")
        self.unitIngredLoabel_2.setScaledContents(False)
        self.unitIngredLoabel_2.setWordWrap(True)
        self.unitIngredLoabel_2.setObjectName("unitIngredLoabel_2")
        self.nutritiansHorizontalLayout.addWidget(self.unitIngredLoabel_2)
        self.fatsLineEdit = QtWidgets.QLineEdit(self.verticalFrame)
        self.fatsLineEdit.setMinimumSize(QtCore.QSize(46, 0))
        self.fatsLineEdit.setMaximumSize(QtCore.QSize(46, 16777215))
        self.fatsLineEdit.setStyleSheet("background-color:#ffffff;\n"
"border-radius:4%;\n"
"border:2px solid rgba(100, 100, 100, 25);\n"
"\n"
"color: #2d2c2c;\n"
"\n"
"height:32px;\n"
"\n"
"padding-left: 8px;\n"
"position:absolute;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"\n"
"font-size:14px;\n"
"left:12px;\n"
"top:8px;")
        self.fatsLineEdit.setText("")
        self.fatsLineEdit.setCursorPosition(0)
        self.fatsLineEdit.setClearButtonEnabled(False)
        self.fatsLineEdit.setObjectName("fatsLineEdit")
        self.nutritiansHorizontalLayout.addWidget(self.fatsLineEdit)
        self.unitIngredLoabel_3 = QtWidgets.QLabel(self.verticalFrame)
        self.unitIngredLoabel_3.setMinimumSize(QtCore.QSize(20, 0))
        self.unitIngredLoabel_3.setMaximumSize(QtCore.QSize(20, 16777215))
        self.unitIngredLoabel_3.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"margin-top: 8px;\n"
"margin-bottom:8px;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"min-width: 20px;\n"
"max-width: 20px;")
        self.unitIngredLoabel_3.setScaledContents(False)
        self.unitIngredLoabel_3.setWordWrap(True)
        self.unitIngredLoabel_3.setObjectName("unitIngredLoabel_3")
        self.nutritiansHorizontalLayout.addWidget(self.unitIngredLoabel_3)
        self.carbohLineEdit = QtWidgets.QLineEdit(self.verticalFrame)
        self.carbohLineEdit.setMinimumSize(QtCore.QSize(46, 0))
        self.carbohLineEdit.setMaximumSize(QtCore.QSize(46, 16777215))
        self.carbohLineEdit.setStyleSheet("background-color:#ffffff;\n"
"border-radius:4%;\n"
"border:2px solid rgba(100, 100, 100, 25);\n"
"\n"
"color: #2d2c2c;\n"
"\n"
"height:32px;\n"
"\n"
"padding-left: 8px;\n"
"position:absolute;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"\n"
"font-size:14px;\n"
"left:12px;\n"
"top:8px;")
        self.carbohLineEdit.setText("")
        self.carbohLineEdit.setCursorPosition(0)
        self.carbohLineEdit.setClearButtonEnabled(False)
        self.carbohLineEdit.setObjectName("carbohLineEdit")
        self.nutritiansHorizontalLayout.addWidget(self.carbohLineEdit)
        self.verticalLayout_2.addLayout(self.nutritiansHorizontalLayout)
        self.ingredientsHeaderLabel = QtWidgets.QLabel(self.verticalFrame)
        self.ingredientsHeaderLabel.setEnabled(True)
        self.ingredientsHeaderLabel.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"\n"
"width: 435px;\n"
"height: 24px;\n"
"\n"
"font: 16pt \"Extra Bold\";\n"
"\n"
"font-weight: 800;\n"
"text-align: left;\n"
"vertical-align: top")
        self.ingredientsHeaderLabel.setObjectName("ingredientsHeaderLabel")
        self.verticalLayout_2.addWidget(self.ingredientsHeaderLabel)
        self.prodListTableView = QtWidgets.QTableView(self.verticalFrame)
        self.prodListTableView.setStyleSheet("QTableView{\n"
"margin-top: 8px;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"border: 3px solid rgba(255, 255, 255, 75);\n"
"border-top-left-radius: 0%;\n"
"border-top-right-radius: 0%;\n"
"}\n"
"\n"
"QTableView::section {\n"
"background-color: rgba(55, 55, 55);\n"
"color: white;\n"
"border: none;\n"
"}\n"
"\n"
"QTableView::item {\n"
"border-style: none;\n"
"border-bottom: rgba(255, 255, 255, 50);\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"border-style: none;\n"
"border-bottom: rgba(255, 255, 255, 50);\n"
"}")
        self.prodListTableView.setObjectName("prodListTableView")
        self.verticalLayout_2.addWidget(self.prodListTableView)
        self.actionsStorageHorizontalLayout = QtWidgets.QHBoxLayout()
        self.actionsStorageHorizontalLayout.setObjectName("actionsStorageHorizontalLayout")
        self.addDishPushButton = QtWidgets.QPushButton(self.verticalFrame)
        self.addDishPushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"margin-top: 16px;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"border: 2 px solid #ADFF81;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}\n"
"\n"
"\n"
"")
        self.addDishPushButton.setObjectName("addDishPushButton")
        self.actionsStorageHorizontalLayout.addWidget(self.addDishPushButton)
        self.verticalLayout_2.addLayout(self.actionsStorageHorizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Умное меню - Добавить блюдо"))
        self.addDishHeaderLabel.setText(_translate("MainWindow", "Информация о блюде"))
        self.unitIngredLoabel_6.setText(_translate("MainWindow", "Название:"))
        self.nameOfDishLineEdit.setPlaceholderText(_translate("MainWindow", "Введите название блюда"))
        self.infoDishPlainTextEdit.setPlaceholderText(_translate("MainWindow", "Введите описание блюда"))
        self.calculateAutoNutritValuecheckBox.setText(_translate("MainWindow", "Заполнять калории автоматически"))
        self.unitIngredLoabel_4.setText(_translate("MainWindow", "Ккал:"))
        self.kaloriesLineEdit.setPlaceholderText(_translate("MainWindow", "Введите количество калорий"))
        self.unitIngredLoabel_1.setText(_translate("MainWindow", "Б:"))
        self.proteinsLineEdit.setPlaceholderText(_translate("MainWindow", "Б:"))
        self.unitIngredLoabel_2.setText(_translate("MainWindow", "Ж:"))
        self.fatsLineEdit.setPlaceholderText(_translate("MainWindow", "Ж:"))
        self.unitIngredLoabel_3.setText(_translate("MainWindow", "У:"))
        self.carbohLineEdit.setPlaceholderText(_translate("MainWindow", "У:"))
        self.ingredientsHeaderLabel.setText(_translate("MainWindow", "Ингредиенты:"))
        self.addDishPushButton.setText(_translate("MainWindow", "Сохранить"))
