# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1442, 695)
        MainWindow.setMinimumSize(QtCore.QSize(1442, 695))
        MainWindow.setMaximumSize(QtCore.QSize(1442, 695))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/bx_dish.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, \n"
"stop:0  rgba(251,239,195,1), \n"
" \n"
"stop:0.6 rgba(230,230,230,1)\n"
"\n"
"stop:0.99 rgba(214,237,192,1));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.products_frame = QtWidgets.QFrame(self.centralwidget)
        self.products_frame.setGeometry(QtCore.QRect(1150, 30, 261, 241))
        self.products_frame.setStyleSheet("background-color: rgba(255, 255, 255, 30%);\n"
"border: 1px solid  rgba(255, 255, 255, 40%);\n"
"border-radius: 10%;\n"
"\n"
"")
        self.products_frame.setObjectName("products_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.products_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.headerProdHorizontalLayout = QtWidgets.QHBoxLayout()
        self.headerProdHorizontalLayout.setObjectName("headerProdHorizontalLayout")
        self.prodHeaderLabel = QtWidgets.QLabel(self.products_frame)
        self.prodHeaderLabel.setEnabled(True)
        self.prodHeaderLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.prodHeaderLabel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.prodHeaderLabel.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"\n"
"width: 435px;\n"
"height: 24px;\n"
"\n"
"font-size: 20px;\n"
"font-family: Inter, \"Extra Bold\";\n"
"font-weight: 800;\n"
"text-align: left;\n"
"vertical-align: top")
        self.prodHeaderLabel.setObjectName("prodHeaderLabel")
        self.headerProdHorizontalLayout.addWidget(self.prodHeaderLabel)
        self.sortProdPushButton = QtWidgets.QPushButton(self.products_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sortProdPushButton.sizePolicy().hasHeightForWidth())
        self.sortProdPushButton.setSizePolicy(sizePolicy)
        self.sortProdPushButton.setStyleSheet("background-color:none;\n"
"height:24px;\n"
"width:24px;\n"
"padding:0px;\n"
"position:relative;\n"
"text-align: center;\n"
"border: none;\n"
"border-radius: 2%;")
        self.sortProdPushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../static/img/bx_sort-a-z.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sortProdPushButton.setIcon(icon1)
        self.sortProdPushButton.setIconSize(QtCore.QSize(24, 24))
        self.sortProdPushButton.setObjectName("sortProdPushButton")
        self.headerProdHorizontalLayout.addWidget(self.sortProdPushButton)
        self.verticalLayout_4.addLayout(self.headerProdHorizontalLayout)
        self.prodListTableView = QtWidgets.QTableView(self.products_frame)
        self.prodListTableView.setStyleSheet("QTableView{\n"
"margin-top: 8px;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"border: 3px solid rgba(255, 255, 255, 75);\n"
"border-top-left-radius: 0%;\n"
"border-top-right-radius: 0%;\n"
"}\n"
"\n"
"QTableView::section {\n"
"background-color: rgba(55, 55, 55);\n"
"color: white;\n"
"border: none;\n"
"}\n"
"\n"
"QTableView::item {\n"
"border-style: none;\n"
"border-bottom: rgba(255, 255, 255, 50);\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"border-style: none;\n"
"border-bottom: rgba(255, 255, 255, 50);\n"
"}")
        self.prodListTableView.setObjectName("prodListTableView")
        self.verticalLayout_4.addWidget(self.prodListTableView)
        self.actionsProdHorizontalLayout = QtWidgets.QHBoxLayout()
        self.actionsProdHorizontalLayout.setObjectName("actionsProdHorizontalLayout")
        self.editProdPushButton = QtWidgets.QPushButton(self.products_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editProdPushButton.sizePolicy().hasHeightForWidth())
        self.editProdPushButton.setSizePolicy(sizePolicy)
        self.editProdPushButton.setMinimumSize(QtCore.QSize(32, 32))
        self.editProdPushButton.setMaximumSize(QtCore.QSize(32, 32))
        self.editProdPushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"border: 2px solid rgba(146, 146, 120, 75);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}")
        self.editProdPushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../static/img/bx_edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editProdPushButton.setIcon(icon2)
        self.editProdPushButton.setIconSize(QtCore.QSize(24, 24))
        self.editProdPushButton.setObjectName("editProdPushButton")
        self.actionsProdHorizontalLayout.addWidget(self.editProdPushButton)
        self.addProdPushButton = QtWidgets.QPushButton(self.products_frame)
        self.addProdPushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"border: 2px solid rgba(146, 146, 120, 75);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}\n"
"\n"
"")
        self.addProdPushButton.setObjectName("addProdPushButton")
        self.actionsProdHorizontalLayout.addWidget(self.addProdPushButton)
        self.deliteProdPushButton = QtWidgets.QPushButton(self.products_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deliteProdPushButton.sizePolicy().hasHeightForWidth())
        self.deliteProdPushButton.setSizePolicy(sizePolicy)
        self.deliteProdPushButton.setMinimumSize(QtCore.QSize(32, 32))
        self.deliteProdPushButton.setMaximumSize(QtCore.QSize(32, 32))
        self.deliteProdPushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"border: 2px solid rgba(146, 146, 120, 75);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}")
        self.deliteProdPushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../static/img/bx_trash.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deliteProdPushButton.setIcon(icon3)
        self.deliteProdPushButton.setIconSize(QtCore.QSize(24, 24))
        self.deliteProdPushButton.setObjectName("deliteProdPushButton")
        self.actionsProdHorizontalLayout.addWidget(self.deliteProdPushButton)
        self.verticalLayout_4.addLayout(self.actionsProdHorizontalLayout)
        self.recomends_frame = QtWidgets.QFrame(self.centralwidget)
        self.recomends_frame.setGeometry(QtCore.QRect(30, 340, 271, 299))
        self.recomends_frame.setStyleSheet("background-color: rgba(255, 255, 255, 30%);\n"
"border: 1px solid  rgba(255, 255, 255, 40%);\n"
"border-radius: 10%;\n"
"\n"
"")
        self.recomends_frame.setObjectName("recomends_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.recomends_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.recomHeaderLabel = QtWidgets.QLabel(self.recomends_frame)
        self.recomHeaderLabel.setEnabled(True)
        self.recomHeaderLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.recomHeaderLabel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.recomHeaderLabel.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"\n"
"width: 435px;\n"
"height: 24px;\n"
"\n"
"font-size: 20px;\n"
"font-family: Inter, \"Extra Bold\";\n"
"font-weight: 800;\n"
"text-align: left;\n"
"vertical-align: top")
        self.recomHeaderLabel.setObjectName("recomHeaderLabel")
        self.verticalLayout_3.addWidget(self.recomHeaderLabel)
        self.infoRecomLabel = QtWidgets.QLabel(self.recomends_frame)
        self.infoRecomLabel.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"margin-top: 8px;\n"
"margin-bottom:8px;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.infoRecomLabel.setScaledContents(False)
        self.infoRecomLabel.setWordWrap(True)
        self.infoRecomLabel.setObjectName("infoRecomLabel")
        self.verticalLayout_3.addWidget(self.infoRecomLabel)
        self.recomendsListTableView = QtWidgets.QTableView(self.recomends_frame)
        self.recomendsListTableView.setObjectName("recomendsListTableView")
        self.verticalLayout_3.addWidget(self.recomendsListTableView)
        self.storage_frame = QtWidgets.QFrame(self.centralwidget)
        self.storage_frame.setGeometry(QtCore.QRect(30, 30, 271, 299))
        self.storage_frame.setStyleSheet("background-color: rgba(255, 255, 255, 30%);\n"
"border: 1px solid  rgba(255, 255, 255, 40%);\n"
"border-radius: 10%;\n"
"\n"
"")
        self.storage_frame.setObjectName("storage_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.storage_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerProdHorizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.headerProdHorizontalLayout_3.setObjectName("headerProdHorizontalLayout_3")
        self.storageHeaderLabel = QtWidgets.QLabel(self.storage_frame)
        self.storageHeaderLabel.setEnabled(True)
        self.storageHeaderLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.storageHeaderLabel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.storageHeaderLabel.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"\n"
"width: 435px;\n"
"height: 24px;\n"
"\n"
"font-size: 20px;\n"
"font-family: Inter, \"Extra Bold\";\n"
"font-weight: 800;\n"
"text-align: left;\n"
"vertical-align: top")
        self.storageHeaderLabel.setObjectName("storageHeaderLabel")
        self.headerProdHorizontalLayout_3.addWidget(self.storageHeaderLabel)
        self.sortStorePushButton_a_z = QtWidgets.QPushButton(self.storage_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sortStorePushButton_a_z.sizePolicy().hasHeightForWidth())
        self.sortStorePushButton_a_z.setSizePolicy(sizePolicy)
        self.sortStorePushButton_a_z.setStyleSheet("background-color:none;\n"
"height:24px;\n"
"width:24px;\n"
"padding:0px;\n"
"position:relative;\n"
"text-align: center;\n"
"border: none;\n"
"border-radius: 2%;")
        self.sortStorePushButton_a_z.setText("")
        self.sortStorePushButton_a_z.setIcon(icon1)
        self.sortStorePushButton_a_z.setIconSize(QtCore.QSize(24, 24))
        self.sortStorePushButton_a_z.setObjectName("sortStorePushButton_a_z")
        self.headerProdHorizontalLayout_3.addWidget(self.sortStorePushButton_a_z)
        self.sortStorePushButton_1_n = QtWidgets.QPushButton(self.storage_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sortStorePushButton_1_n.sizePolicy().hasHeightForWidth())
        self.sortStorePushButton_1_n.setSizePolicy(sizePolicy)
        self.sortStorePushButton_1_n.setStyleSheet("background-color:none;\n"
"height:24px;\n"
"width:24px;\n"
"padding:0px;\n"
"position:relative;\n"
"text-align: center;\n"
"border: none;\n"
"border-radius: 2%;")
        self.sortStorePushButton_1_n.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../static/img/bx_sort-1-n.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sortStorePushButton_1_n.setIcon(icon4)
        self.sortStorePushButton_1_n.setIconSize(QtCore.QSize(24, 24))
        self.sortStorePushButton_1_n.setObjectName("sortStorePushButton_1_n")
        self.headerProdHorizontalLayout_3.addWidget(self.sortStorePushButton_1_n)
        self.verticalLayout.addLayout(self.headerProdHorizontalLayout_3)
        self.storageListTableView = QtWidgets.QTableView(self.storage_frame)
        self.storageListTableView.setStyleSheet("QTableView{\n"
"background-color: rgba(255, 255, 255, 50);\n"
"border: 3px solid rgba(255, 255, 255, 75);\n"
"margin-top: 8px;\n"
"}\n"
"\n"
"QTableView::section {\n"
"background-color: rgba(55, 55, 55);\n"
"color: white;\n"
"border: none;\n"
"}\n"
"\n"
"QTableView::item {\n"
"border-style: none;\n"
"border-bottom: rgba(255, 255, 255, 50);\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"border-style: none;\n"
"border-bottom: rgba(255, 255, 255, 50);\n"
"background-color: rgba(255, 255, 255, 85);\n"
"}")
        self.storageListTableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.storageListTableView.setShowGrid(False)
        self.storageListTableView.setObjectName("storageListTableView")
        self.storageListTableView.horizontalHeader().setDefaultSectionSize(50)
        self.verticalLayout.addWidget(self.storageListTableView)
        self.actionsStorageHorizontalLayout = QtWidgets.QHBoxLayout()
        self.actionsStorageHorizontalLayout.setObjectName("actionsStorageHorizontalLayout")
        self.editStoraItemPushButton = QtWidgets.QPushButton(self.storage_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editStoraItemPushButton.sizePolicy().hasHeightForWidth())
        self.editStoraItemPushButton.setSizePolicy(sizePolicy)
        self.editStoraItemPushButton.setMinimumSize(QtCore.QSize(32, 32))
        self.editStoraItemPushButton.setMaximumSize(QtCore.QSize(32, 32))
        self.editStoraItemPushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"border: 2px solid rgba(146, 146, 120, 75);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}")
        self.editStoraItemPushButton.setText("")
        self.editStoraItemPushButton.setIcon(icon2)
        self.editStoraItemPushButton.setIconSize(QtCore.QSize(24, 24))
        self.editStoraItemPushButton.setObjectName("editStoraItemPushButton")
        self.actionsStorageHorizontalLayout.addWidget(self.editStoraItemPushButton)
        self.addStorageItemPushButton = QtWidgets.QPushButton(self.storage_frame)
        self.addStorageItemPushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"border: 2px solid rgba(146, 146, 120, 75);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}\n"
"\n"
"\n"
"")
        self.addStorageItemPushButton.setIconSize(QtCore.QSize(24, 24))
        self.addStorageItemPushButton.setObjectName("addStorageItemPushButton")
        self.actionsStorageHorizontalLayout.addWidget(self.addStorageItemPushButton)
        self.deliteStorageItemPushButton = QtWidgets.QPushButton(self.storage_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deliteStorageItemPushButton.sizePolicy().hasHeightForWidth())
        self.deliteStorageItemPushButton.setSizePolicy(sizePolicy)
        self.deliteStorageItemPushButton.setMinimumSize(QtCore.QSize(32, 32))
        self.deliteStorageItemPushButton.setMaximumSize(QtCore.QSize(32, 32))
        self.deliteStorageItemPushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"border: 2px solid rgba(146, 146, 120, 75);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}")
        self.deliteStorageItemPushButton.setText("")
        self.deliteStorageItemPushButton.setIcon(icon3)
        self.deliteStorageItemPushButton.setIconSize(QtCore.QSize(24, 24))
        self.deliteStorageItemPushButton.setObjectName("deliteStorageItemPushButton")
        self.actionsStorageHorizontalLayout.addWidget(self.deliteStorageItemPushButton)
        self.verticalLayout.addLayout(self.actionsStorageHorizontalLayout)
        self.menu_frame = QtWidgets.QFrame(self.centralwidget)
        self.menu_frame.setGeometry(QtCore.QRect(320, 30, 811, 371))
        self.menu_frame.setStyleSheet("background-color: rgba(255, 255, 255, 30%);\n"
"border: 1px solid  rgba(255, 255, 255, 40%);\n"
"border-radius: 10%;\n"
"\n"
"")
        self.menu_frame.setObjectName("menu_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.menu_frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.MenuHeaderLabel = QtWidgets.QLabel(self.menu_frame)
        self.MenuHeaderLabel.setEnabled(True)
        self.MenuHeaderLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.MenuHeaderLabel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.MenuHeaderLabel.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"\n"
"width: 435px;\n"
"height: 24px;\n"
"\n"
"font-size: 20px;\n"
"font-family: Inter, \"Extra Bold\";\n"
"font-weight: 800;\n"
"text-align: left;\n"
"vertical-align: top")
        self.MenuHeaderLabel.setObjectName("MenuHeaderLabel")
        self.verticalLayout_6.addWidget(self.MenuHeaderLabel)
        self.infoMenuLabel = QtWidgets.QLabel(self.menu_frame)
        self.infoMenuLabel.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"margin-top: 8px;\n"
"margin-bottom:8px;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.infoMenuLabel.setScaledContents(False)
        self.infoMenuLabel.setWordWrap(True)
        self.infoMenuLabel.setIndent(0)
        self.infoMenuLabel.setObjectName("infoMenuLabel")
        self.verticalLayout_6.addWidget(self.infoMenuLabel)
        self.actionsMenuHorizontalLayout = QtWidgets.QHBoxLayout()
        self.actionsMenuHorizontalLayout.setObjectName("actionsMenuHorizontalLayout")
        self.addMenuPushButton = QtWidgets.QPushButton(self.menu_frame)
        self.addMenuPushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"border: 2px solid rgba(146, 146, 120, 75);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}\n"
"\n"
"\n"
"")
        self.addMenuPushButton.setObjectName("addMenuPushButton")
        self.actionsMenuHorizontalLayout.addWidget(self.addMenuPushButton)
        self.editMenuPushButton = QtWidgets.QPushButton(self.menu_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editMenuPushButton.sizePolicy().hasHeightForWidth())
        self.editMenuPushButton.setSizePolicy(sizePolicy)
        self.editMenuPushButton.setMinimumSize(QtCore.QSize(32, 32))
        self.editMenuPushButton.setMaximumSize(QtCore.QSize(32, 32))
        self.editMenuPushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"border: 2px solid rgba(146, 146, 120, 75);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}")
        self.editMenuPushButton.setText("")
        self.editMenuPushButton.setIcon(icon2)
        self.editMenuPushButton.setIconSize(QtCore.QSize(24, 24))
        self.editMenuPushButton.setObjectName("editMenuPushButton")
        self.actionsMenuHorizontalLayout.addWidget(self.editMenuPushButton)
        self.verticalLayout_6.addLayout(self.actionsMenuHorizontalLayout)
        self.menuListTableView = QtWidgets.QTableView(self.menu_frame)
        self.menuListTableView.setStyleSheet("QTableView{\n"
"background-color: rgba(255, 255, 255, 50);\n"
"border: 3px solid rgba(255, 255, 255, 75);\n"
"border-top-left-radius: 0%;\n"
"border-top-right-radius: 0%;\n"
"}\n"
"\n"
"QTableView::section {\n"
"background-color: rgba(55, 55, 55);\n"
"color: white;\n"
"border: none;\n"
"}\n"
"\n"
"QTableView::item {\n"
"border-style: none;\n"
"border-bottom: rgba(255, 255, 255, 50);\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"border-style: none;\n"
"border-bottom: rgba(255, 255, 255, 50);\n"
"}")
        self.menuListTableView.setObjectName("menuListTableView")
        self.verticalLayout_6.addWidget(self.menuListTableView)
        self.dishes_frame = QtWidgets.QFrame(self.centralwidget)
        self.dishes_frame.setGeometry(QtCore.QRect(1150, 280, 261, 262))
        self.dishes_frame.setStyleSheet("background-color: rgba(255, 255, 255, 30%);\n"
"border: 1px solid  rgba(255, 255, 255, 40%);\n"
"border-radius: 10%;\n"
"\n"
"")
        self.dishes_frame.setObjectName("dishes_frame")
        self.Dishes_Layout_2 = QtWidgets.QVBoxLayout(self.dishes_frame)
        self.Dishes_Layout_2.setObjectName("Dishes_Layout_2")
        self.headerProdHorizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.headerProdHorizontalLayout_2.setObjectName("headerProdHorizontalLayout_2")
        self.dishesHeaderLabel = QtWidgets.QLabel(self.dishes_frame)
        self.dishesHeaderLabel.setEnabled(True)
        self.dishesHeaderLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.dishesHeaderLabel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.dishesHeaderLabel.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"\n"
"width: 435px;\n"
"height: 24px;\n"
"\n"
"font-size: 20px;\n"
"font-family: Inter, \"Extra Bold\";\n"
"font-weight: 800;\n"
"text-align: left;\n"
"vertical-align: top")
        self.dishesHeaderLabel.setObjectName("dishesHeaderLabel")
        self.headerProdHorizontalLayout_2.addWidget(self.dishesHeaderLabel)
        self.sortDishesPushButton = QtWidgets.QPushButton(self.dishes_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sortDishesPushButton.sizePolicy().hasHeightForWidth())
        self.sortDishesPushButton.setSizePolicy(sizePolicy)
        self.sortDishesPushButton.setStyleSheet("background-color:none;\n"
"height:24px;\n"
"width:24px;\n"
"padding:0px;\n"
"position:relative;\n"
"text-align: center;\n"
"border: none;\n"
"border-radius: 2%;")
        self.sortDishesPushButton.setText("")
        self.sortDishesPushButton.setIcon(icon1)
        self.sortDishesPushButton.setIconSize(QtCore.QSize(24, 24))
        self.sortDishesPushButton.setObjectName("sortDishesPushButton")
        self.headerProdHorizontalLayout_2.addWidget(self.sortDishesPushButton)
        self.Dishes_Layout_2.addLayout(self.headerProdHorizontalLayout_2)
        self.dishListTableView = QtWidgets.QTableView(self.dishes_frame)
        self.dishListTableView.setStyleSheet("margin-top: 8px;")
        self.dishListTableView.setObjectName("dishListTableView")
        self.Dishes_Layout_2.addWidget(self.dishListTableView)
        self.actionsDishHorizontalLayout = QtWidgets.QHBoxLayout()
        self.actionsDishHorizontalLayout.setObjectName("actionsDishHorizontalLayout")
        self.editDishPushButton = QtWidgets.QPushButton(self.dishes_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editDishPushButton.sizePolicy().hasHeightForWidth())
        self.editDishPushButton.setSizePolicy(sizePolicy)
        self.editDishPushButton.setMinimumSize(QtCore.QSize(32, 32))
        self.editDishPushButton.setMaximumSize(QtCore.QSize(32, 32))
        self.editDishPushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"border: 2px solid rgba(146, 146, 120, 75);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}")
        self.editDishPushButton.setText("")
        self.editDishPushButton.setIcon(icon2)
        self.editDishPushButton.setIconSize(QtCore.QSize(24, 24))
        self.editDishPushButton.setObjectName("editDishPushButton")
        self.actionsDishHorizontalLayout.addWidget(self.editDishPushButton)
        self.addDishPushButton = QtWidgets.QPushButton(self.dishes_frame)
        self.addDishPushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"border: 2px solid rgba(146, 146, 120, 75);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}\n"
"")
        self.addDishPushButton.setObjectName("addDishPushButton")
        self.actionsDishHorizontalLayout.addWidget(self.addDishPushButton)
        self.deliteDishPushButton = QtWidgets.QPushButton(self.dishes_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deliteDishPushButton.sizePolicy().hasHeightForWidth())
        self.deliteDishPushButton.setSizePolicy(sizePolicy)
        self.deliteDishPushButton.setMinimumSize(QtCore.QSize(32, 32))
        self.deliteDishPushButton.setMaximumSize(QtCore.QSize(32, 32))
        self.deliteDishPushButton.setStyleSheet("QPushButton{\n"
"height:32px;\n"
"width:auto;\n"
"\n"
"color: #30353B;\n"
"background: #ADDC81;\n"
"\n"
"text-align:center;\n"
"vertical-align:center;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"font-weight: bold;\n"
"\n"
"border-radius:4%;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #AAAA81;\n"
"border: 2px solid rgba(146, 146, 120, 75);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: #AAAAFF;\n"
"}")
        self.deliteDishPushButton.setText("")
        self.deliteDishPushButton.setIcon(icon3)
        self.deliteDishPushButton.setIconSize(QtCore.QSize(24, 24))
        self.deliteDishPushButton.setObjectName("deliteDishPushButton")
        self.actionsDishHorizontalLayout.addWidget(self.deliteDishPushButton)
        self.Dishes_Layout_2.addLayout(self.actionsDishHorizontalLayout)
        self.history_frame = QtWidgets.QFrame(self.centralwidget)
        self.history_frame.setGeometry(QtCore.QRect(320, 420, 811, 211))
        self.history_frame.setStyleSheet("background-color: rgba(255, 255, 255, 30%);\n"
"border: 1px solid  rgba(255, 255, 255, 40%);\n"
"border-radius: 10%;\n"
"\n"
"")
        self.history_frame.setObjectName("history_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.history_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hostoryHeaderLabel = QtWidgets.QLabel(self.history_frame)
        self.hostoryHeaderLabel.setEnabled(True)
        self.hostoryHeaderLabel.setMinimumSize(QtCore.QSize(0, 24))
        self.hostoryHeaderLabel.setMaximumSize(QtCore.QSize(787, 24))
        self.hostoryHeaderLabel.setStyleSheet("background-color: none;\n"
"color: #2d2c2c;\n"
"border:none;\n"
"\n"
"width: 435px;\n"
"height: 24px;\n"
"\n"
"font-size: 20px;\n"
"font-family: Inter, \"Extra Bold\";\n"
"font-weight: 800;\n"
"text-align: left;\n"
"vertical-align: top")
        self.hostoryHeaderLabel.setObjectName("hostoryHeaderLabel")
        self.verticalLayout_2.addWidget(self.hostoryHeaderLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.history_card_frame_1 = QtWidgets.QFrame(self.history_frame)
        self.history_card_frame_1.setStyleSheet("background-color: rgba(255, 255, 255, 30%);\n"
"border: 1px solid  rgba(255, 255, 255, 40%);\n"
"border-radius: 10%;\n"
"\n"
"")
        self.history_card_frame_1.setObjectName("history_card_frame_1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.history_card_frame_1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.dateLabel = QtWidgets.QLabel(self.history_card_frame_1)
        self.dateLabel.setStyleSheet("color:#b4b4b4;\n"
"background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;")
        self.dateLabel.setScaledContents(False)
        self.dateLabel.setWordWrap(True)
        self.dateLabel.setObjectName("dateLabel")
        self.verticalLayout_8.addWidget(self.dateLabel)
        self.listFoodVerticalLayout = QtWidgets.QVBoxLayout()
        self.listFoodVerticalLayout.setObjectName("listFoodVerticalLayout")
        self.breakfastLabel = QtWidgets.QLabel(self.history_card_frame_1)
        self.breakfastLabel.setStyleSheet("background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.breakfastLabel.setScaledContents(False)
        self.breakfastLabel.setWordWrap(True)
        self.breakfastLabel.setObjectName("breakfastLabel")
        self.listFoodVerticalLayout.addWidget(self.breakfastLabel)
        self.lunchLabel = QtWidgets.QLabel(self.history_card_frame_1)
        self.lunchLabel.setStyleSheet("background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.lunchLabel.setScaledContents(False)
        self.lunchLabel.setWordWrap(True)
        self.lunchLabel.setObjectName("lunchLabel")
        self.listFoodVerticalLayout.addWidget(self.lunchLabel)
        self.dinerLabel = QtWidgets.QLabel(self.history_card_frame_1)
        self.dinerLabel.setStyleSheet("background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.dinerLabel.setScaledContents(False)
        self.dinerLabel.setWordWrap(True)
        self.dinerLabel.setObjectName("dinerLabel")
        self.listFoodVerticalLayout.addWidget(self.dinerLabel)
        self.verticalLayout_8.addLayout(self.listFoodVerticalLayout)
        self.cardBorderLine = QtWidgets.QFrame(self.history_card_frame_1)
        self.cardBorderLine.setStyleSheet("background-color: rgba(173, 220, 130, 75)")
        self.cardBorderLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cardBorderLine.setLineWidth(1)
        self.cardBorderLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.cardBorderLine.setObjectName("cardBorderLine")
        self.verticalLayout_8.addWidget(self.cardBorderLine)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.kaloriesLabel = QtWidgets.QLabel(self.history_card_frame_1)
        self.kaloriesLabel.setStyleSheet("background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.kaloriesLabel.setScaledContents(False)
        self.kaloriesLabel.setWordWrap(True)
        self.kaloriesLabel.setObjectName("kaloriesLabel")
        self.horizontalLayout_2.addWidget(self.kaloriesLabel)
        self.foodvalueLabel = QtWidgets.QLabel(self.history_card_frame_1)
        self.foodvalueLabel.setStyleSheet("background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.foodvalueLabel.setScaledContents(False)
        self.foodvalueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.foodvalueLabel.setWordWrap(True)
        self.foodvalueLabel.setObjectName("foodvalueLabel")
        self.horizontalLayout_2.addWidget(self.foodvalueLabel)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.history_card_frame_1)
        self.history_card_frame_2 = QtWidgets.QFrame(self.history_frame)
        self.history_card_frame_2.setStyleSheet("background-color: rgba(255, 255, 255, 30%);\n"
"border: 1px solid  rgba(255, 255, 255, 40%);\n"
"border-radius: 10%;\n"
"\n"
"")
        self.history_card_frame_2.setObjectName("history_card_frame_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.history_card_frame_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.dateLabel_2 = QtWidgets.QLabel(self.history_card_frame_2)
        self.dateLabel_2.setStyleSheet("color:#b4b4b4;\n"
"background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;")
        self.dateLabel_2.setScaledContents(False)
        self.dateLabel_2.setWordWrap(True)
        self.dateLabel_2.setObjectName("dateLabel_2")
        self.verticalLayout_9.addWidget(self.dateLabel_2)
        self.listFoodVerticalLayout_2 = QtWidgets.QVBoxLayout()
        self.listFoodVerticalLayout_2.setObjectName("listFoodVerticalLayout_2")
        self.breakfastLabel_2 = QtWidgets.QLabel(self.history_card_frame_2)
        self.breakfastLabel_2.setStyleSheet("background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.breakfastLabel_2.setScaledContents(False)
        self.breakfastLabel_2.setWordWrap(True)
        self.breakfastLabel_2.setObjectName("breakfastLabel_2")
        self.listFoodVerticalLayout_2.addWidget(self.breakfastLabel_2)
        self.lunchLabel_2 = QtWidgets.QLabel(self.history_card_frame_2)
        self.lunchLabel_2.setStyleSheet("background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.lunchLabel_2.setScaledContents(False)
        self.lunchLabel_2.setWordWrap(True)
        self.lunchLabel_2.setObjectName("lunchLabel_2")
        self.listFoodVerticalLayout_2.addWidget(self.lunchLabel_2)
        self.dinerLabel_2 = QtWidgets.QLabel(self.history_card_frame_2)
        self.dinerLabel_2.setStyleSheet("background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.dinerLabel_2.setScaledContents(False)
        self.dinerLabel_2.setWordWrap(True)
        self.dinerLabel_2.setObjectName("dinerLabel_2")
        self.listFoodVerticalLayout_2.addWidget(self.dinerLabel_2)
        self.verticalLayout_9.addLayout(self.listFoodVerticalLayout_2)
        self.cardBorderLine_2 = QtWidgets.QFrame(self.history_card_frame_2)
        self.cardBorderLine_2.setStyleSheet("background-color: rgba(173, 220, 130, 75)")
        self.cardBorderLine_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cardBorderLine_2.setLineWidth(1)
        self.cardBorderLine_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.cardBorderLine_2.setObjectName("cardBorderLine_2")
        self.verticalLayout_9.addWidget(self.cardBorderLine_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.kaloriesLabel_2 = QtWidgets.QLabel(self.history_card_frame_2)
        self.kaloriesLabel_2.setStyleSheet("background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.kaloriesLabel_2.setScaledContents(False)
        self.kaloriesLabel_2.setWordWrap(True)
        self.kaloriesLabel_2.setObjectName("kaloriesLabel_2")
        self.horizontalLayout_7.addWidget(self.kaloriesLabel_2)
        self.foodvalueLabel_2 = QtWidgets.QLabel(self.history_card_frame_2)
        self.foodvalueLabel_2.setStyleSheet("background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.foodvalueLabel_2.setScaledContents(False)
        self.foodvalueLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.foodvalueLabel_2.setWordWrap(True)
        self.foodvalueLabel_2.setObjectName("foodvalueLabel_2")
        self.horizontalLayout_7.addWidget(self.foodvalueLabel_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout.addWidget(self.history_card_frame_2)
        self.history_card_frame_3 = QtWidgets.QFrame(self.history_frame)
        self.history_card_frame_3.setStyleSheet("background-color: rgba(255, 255, 255, 30%);\n"
"border: 1px solid  rgba(255, 255, 255, 40%);\n"
"border-radius: 10%;\n"
"\n"
"")
        self.history_card_frame_3.setObjectName("history_card_frame_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.history_card_frame_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.dateLabel_3 = QtWidgets.QLabel(self.history_card_frame_3)
        self.dateLabel_3.setStyleSheet("color:#b4b4b4;\n"
"background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;")
        self.dateLabel_3.setScaledContents(False)
        self.dateLabel_3.setWordWrap(True)
        self.dateLabel_3.setObjectName("dateLabel_3")
        self.verticalLayout_10.addWidget(self.dateLabel_3)
        self.listFoodVerticalLayout_3 = QtWidgets.QVBoxLayout()
        self.listFoodVerticalLayout_3.setObjectName("listFoodVerticalLayout_3")
        self.breakfastLabel_3 = QtWidgets.QLabel(self.history_card_frame_3)
        self.breakfastLabel_3.setStyleSheet("background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.breakfastLabel_3.setScaledContents(False)
        self.breakfastLabel_3.setWordWrap(True)
        self.breakfastLabel_3.setObjectName("breakfastLabel_3")
        self.listFoodVerticalLayout_3.addWidget(self.breakfastLabel_3)
        self.lunchLabel_3 = QtWidgets.QLabel(self.history_card_frame_3)
        self.lunchLabel_3.setStyleSheet("background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.lunchLabel_3.setScaledContents(False)
        self.lunchLabel_3.setWordWrap(True)
        self.lunchLabel_3.setObjectName("lunchLabel_3")
        self.listFoodVerticalLayout_3.addWidget(self.lunchLabel_3)
        self.dinerLabel_3 = QtWidgets.QLabel(self.history_card_frame_3)
        self.dinerLabel_3.setStyleSheet("background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.dinerLabel_3.setScaledContents(False)
        self.dinerLabel_3.setWordWrap(True)
        self.dinerLabel_3.setObjectName("dinerLabel_3")
        self.listFoodVerticalLayout_3.addWidget(self.dinerLabel_3)
        self.verticalLayout_10.addLayout(self.listFoodVerticalLayout_3)
        self.cardBorderLine_3 = QtWidgets.QFrame(self.history_card_frame_3)
        self.cardBorderLine_3.setStyleSheet("background-color: rgba(173, 220, 130, 75)")
        self.cardBorderLine_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cardBorderLine_3.setLineWidth(1)
        self.cardBorderLine_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.cardBorderLine_3.setObjectName("cardBorderLine_3")
        self.verticalLayout_10.addWidget(self.cardBorderLine_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.kaloriesLabel_3 = QtWidgets.QLabel(self.history_card_frame_3)
        self.kaloriesLabel_3.setStyleSheet("background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.kaloriesLabel_3.setScaledContents(False)
        self.kaloriesLabel_3.setWordWrap(True)
        self.kaloriesLabel_3.setObjectName("kaloriesLabel_3")
        self.horizontalLayout_8.addWidget(self.kaloriesLabel_3)
        self.foodvalueLabel_3 = QtWidgets.QLabel(self.history_card_frame_3)
        self.foodvalueLabel_3.setStyleSheet("background-color: none;\n"
"border: none;\n"
"\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:12px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"\n"
"color:#30353b;\n"
"text-align:left;\n"
"vertical-align:text-top;\n"
"font-size:14px;\n"
"font-family:Inter;\n"
"line-height:auto;\n"
"border-style:hidden;\n"
"outline:none;\n"
"width:435px;")
        self.foodvalueLabel_3.setScaledContents(False)
        self.foodvalueLabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.foodvalueLabel_3.setWordWrap(True)
        self.foodvalueLabel_3.setObjectName("foodvalueLabel_3")
        self.horizontalLayout_8.addWidget(self.foodvalueLabel_3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout.addWidget(self.history_card_frame_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Умное меню"))
        self.prodHeaderLabel.setText(_translate("MainWindow", "Продукты:"))
        self.addProdPushButton.setText(_translate("MainWindow", "Добавить продукт"))
        self.recomHeaderLabel.setText(_translate("MainWindow", "Рекомендации"))
        self.infoRecomLabel.setText(_translate("MainWindow", "У вас давно лежит картошка. Посмотрите, что можно из нее приготовить:\n"
""))
        self.storageHeaderLabel.setText(_translate("MainWindow", "Запасы"))
        self.addStorageItemPushButton.setText(_translate("MainWindow", "Добавить"))
        self.MenuHeaderLabel.setText(_translate("MainWindow", "Меню на сегодня"))
        self.infoMenuLabel.setText(_translate("MainWindow", "На сегодня у вас не составлено меню. \n"
"Для составления меню нажмите кнопку ниже"))
        self.addMenuPushButton.setText(_translate("MainWindow", "Составить меню"))
        self.dishesHeaderLabel.setText(_translate("MainWindow", "Блюда:"))
        self.addDishPushButton.setText(_translate("MainWindow", "Добавить блюдо"))
        self.hostoryHeaderLabel.setText(_translate("MainWindow", "История"))
        self.dateLabel.setText(_translate("MainWindow", "11.11.2024, пн"))
        self.breakfastLabel.setText(_translate("MainWindow", "Завтрака нет"))
        self.lunchLabel.setText(_translate("MainWindow", "Обеда нет"))
        self.dinerLabel.setText(_translate("MainWindow", "Ужина нет"))
        self.kaloriesLabel.setText(_translate("MainWindow", "0 Ккал"))
        self.foodvalueLabel.setText(_translate("MainWindow", "Б: 0 Ж: 0 У: 0"))
        self.dateLabel_2.setText(_translate("MainWindow", "11.11.2024, пн"))
        self.breakfastLabel_2.setText(_translate("MainWindow", "Завтрака нет"))
        self.lunchLabel_2.setText(_translate("MainWindow", "Обеда нет"))
        self.dinerLabel_2.setText(_translate("MainWindow", "Ужина нет"))
        self.kaloriesLabel_2.setText(_translate("MainWindow", "0 Ккал"))
        self.foodvalueLabel_2.setText(_translate("MainWindow", "Б: 0 Ж: 0 У: 0"))
        self.dateLabel_3.setText(_translate("MainWindow", "11.11.2024, пн"))
        self.breakfastLabel_3.setText(_translate("MainWindow", "Завтрака нет"))
        self.lunchLabel_3.setText(_translate("MainWindow", "Обеда нет"))
        self.dinerLabel_3.setText(_translate("MainWindow", "Ужина нет"))
        self.kaloriesLabel_3.setText(_translate("MainWindow", "0 Ккал"))
        self.foodvalueLabel_3.setText(_translate("MainWindow", "Б: 0 Ж: 0 У: 0"))
import res-project_rc
